### ISSUE TITLE
Oktoberfest update

### ISSUE THREAD

**Issue by realkarmakun** [DRG-Modding/Audio-Modding-Template#1]
So I guess mods built on this template does not actually work for current update. Maybe there a guide to getting original uncooked sound cues from updated game?

**Comment by Buckminsterfullerene02** [comment]
Thanks for reminding me. I will update this as soon as I have time to.

Mods built on this template should still work in the game, as long as the cue/audio file that they are replacing still exists in the same location as before.

Currently the only way to get uncooked sound cues from the game is using a tool that is closed source as it is still WIP. So people will have to rely on me to update this repository for the time being.

**Comment by Buckminsterfullerene02** [comment]
Done!
